### ISSUE TITLE
error: passing argument 2 of 's_wifi_setup_test_cb' discards 'const' qualifier from pointer target type [-Werror]

### ISSUE THREAD

**Issue by plusonedev** [tripflex/captive-portal#7]
I cloned the captive-portal-wifi-stack-demo and built with
> mos build --platform esp8266

and got this error
> error: passing argument 2 of 's_wifi_setup_test_cb' discards 'const' qualifier from pointer target type [-Werror]
>              s_wifi_setup_test_cb( true, sp_test_sta_vals->ssid, sp_test_sta_vals->pass, s_wifi_setup_test_userdata );

After troubleshooting for a while I tried building a fresh copy of the demo-js app for a sanity check against any issues I may have upstream and this compiled fine.
>The Mongoose OS command line tool
Version: 2.14.0
Build ID: 2.14.0~brew
Update channel: release

**Comment by tripflex** [comment]
So the weird thing about this ... my libs don't actually define any `const` and the `sp_test_sta_vals` is a struct of `mgos_wifi_setup_sta` which does not have any const either:
https://mongoose-os.com/docs/mongoose-os/api/net/wifi.md#mgos_wifi_setup_sta

Does it give you any more details?  What line number? Any other kind of error/warning output regarding this?

**Comment by tripflex** [comment]
@plusonedev this has been fixed in the appropriate lib this issue is related to:
https://github.com/tripflex/captive-portal-wifi-setup/issues/5

**Comment by plusonedev** [comment]
Fantastic!  Thanks for the update!
